frase = "Seremos os melhores programadores"
print (frase[15])
print (frase[9:13])
print (frase[9:50])
print (frase[9:20:2])
print (frase[:5])
print (frase[9::3])
print (frase[:20:2])
print (len(frase))
print(frase.count('e',0,15))
print(frase.find('es'))
print(frase.find('frovign'))
print("curso" in frase)
print(frase.replace('melhores','the bests'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())

frase = "    Os melhores programadores        "
print(frase)
print(frase.strip())
print(frase.rstrip())
print(frase.lstrip())
print(frase.split())
print('*'.join(frase))